In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int32


In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
2
(3, 4)
12
int32


In [4]:
arr=np.array([[1,2,3,4]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2
(1, 4)
4
int32


In [5]:
arr=np.array([[[1,2,3,4]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[1 2 3 4]]]
<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int32


In [8]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
<class 'numpy.ndarray'>
3
(2, 2, 5)
20
int32


In [16]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>
3
(2, 3, 3)
18
int32


In [3]:
#iterations
arr=np.array([1,2,3,4,])
for i in arr:
    print(i)

1
2
3
4


In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
for i in arr:
    for j in i:
        print(j,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [10]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
for i in arr:
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [9]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
for i in np.nditer(arr):
    print(i,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [20]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
for i in np.ndenumerate(arr):
    print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((0, 2, 0), 7)
((0, 2, 1), 8)
((0, 2, 2), 9)
((1, 0, 0), 10)
((1, 0, 1), 11)
((1, 0, 2), 12)
((1, 1, 0), 13)
((1, 1, 1), 14)
((1, 1, 2), 15)
((1, 2, 0), 16)
((1, 2, 1), 17)
((1, 2, 2), 18)


In [3]:
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [5]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)

[[10 20 30 40]
 [50 60 70 80]]


In [6]:
arr=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]],[[130,140,150],[160,170,180]]])
print(arr)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[130 140 150]
  [160 170 180]]]


In [19]:
#arange([start],stop,[step])
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print()
print(arr[0])
print()
print(arr[1][1])
print()
print(arr[2][1][0])
print()
print(arr[::-1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[13 14 15]

22

[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


In [21]:
arr=np.array([1,2,3,4],ndmin=10)
print(arr)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


In [24]:
#special filled array
arr=np.zeros(4,dtype=int)
print(arr)

[0 0 0 0]


In [31]:
arr=np.zeros((4,4,4),dtype=int)
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [33]:
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [34]:
arr=np.ones((4,4,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
arr=np.full((4,4,4),4)
print(arr)

[[[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]]


In [41]:
arr=np.eye(4,4)
print(arr)
print()
print(arr[::-1])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [4]:
arr=np.arange(1,25).reshape(2,3,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [6]:
# Evenly spaced Array
# Linpace(start,endpoint,[numbers])
# by default - 50
arr=np.linspace(0,10,5)
print(arr)
print(len(arr))

[ 0.   2.5  5.   7.5 10. ]
5


In [7]:
arr=np.linspace(1,20,5)
print(arr)

[ 1.    5.75 10.5  15.25 20.  ]


In [9]:
arr=np.linspace(0,50)
print(arr)
print(len(arr))

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]
50


In [10]:
# Array with random  number
# randint
arr=np.random.randint(20,30,(2,2,5))
print(arr)

[[[23 27 20 23 22]
  [26 20 22 23 27]]

 [[29 26 25 27 20]
  [22 24 20 24 25]]]


In [12]:
arr=np.random.rand(2,2,5)
print(arr)

[[[0.04847411 0.30576769 0.98898148 0.84169556 0.01027218]
  [0.33780809 0.15623668 0.74829446 0.05850653 0.8620302 ]]

 [[0.45228651 0.00484859 0.36826047 0.28759734 0.1451493 ]
  [0.85508902 0.13562046 0.68316468 0.22206161 0.09091433]]]


In [15]:
arr=np.random.randn(4,6)
print(arr)

[[-0.1527275  -0.62276016 -0.16450608 -0.25495046  1.72089341  1.58162296]
 [ 1.71592855  1.25242817 -0.12589366  0.66882172 -1.41693812  1.84179978]
 [ 0.98767886 -0.08802095  0.89597463  1.45685213 -0.12950248  0.45738177]
 [-2.38539729  3.36228194  0.53929474  0.41448944  0.13965325  0.93774636]]
