In [1]:
#Broadcasting is a powerful mechanism that allows arithmetic and logical operations on arrays of different shapes and sizes without explicitely creating multiple copies
#of smaller array.
#Basic Rules :
#dimesion padding 
#dimension compatibiity: equal in size or one of them is one.

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
arr1=arr+3
print(arr1)

[1 2 3 4]
[4 5 6 7]


In [3]:
arr1=np.array([1,2,3,4])
print(arr1)
arr2=np.array([[10],[20],[30],[40]])
print(arr2)
arr=arr1+arr2
print(arr)

[1 2 3 4]
[[10]
 [20]
 [30]
 [40]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [ ]:
arr1=np.arange(1,9)
print(arr1)
