### Join Two Array

In [1]:
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)
arr2=np.array([5,6,7,8])
print(arr2)
print()
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4]
[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [3]:
arr1=np.array([1,2,3,4])
print(arr1)
arr2=np.array([5,6,7])
print(arr2)
print()
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4]
[5 6 7]

[1 2 3 4 5 6 7]


In [6]:
arr1=np.array([[1,2,3,4,5]])
print(arr1)
arr2=np.array([[6,7,8,9,10]])
print(arr2)
print()
arr_new=np.concatenate((arr1,arr2))
print(arr_new)
arr_new1=np.concatenate((arr1,arr2),axis=1)
print(arr_new1)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [7]:
arr1=np.array([[1,2,3,4,5]])
print(arr1)
arr2=np.array([[6,7,8,9]])
print(arr2)
print()
arr_new=np.concatenate((arr1,arr2),axis=1)
print(arr_new)

[[1 2 3 4 5]]
[[6 7 8 9]]

[[1 2 3 4 5 6 7 8 9]]


In [8]:
arr1=np.array([[1,2,3,4,5]])
print(arr1)
arr2=np.array([[6,7,8,9,10]])
print(arr2)
print()
arr_new1=np.concatenate((arr1,arr2),axis=0)
print(arr_new1)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
arr1=np.array([[1,2,3,4,5]])
print(arr1)
arr2=np.array([6,7,8,9,10])
print(arr2)
print()
arr_new1=np.concatenate((arr1,arr2),axis=1)
print(arr_new1)

[[1 2 3 4 5]]
[ 6  7  8  9 10]



ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [10]:
arr1=np.array([[1,2],[3,4],[5,6]])
print(arr1)
arr2=np.array([[7,8],[9,10],[11,12]])
print(arr2)
print()
arr_new1=np.concatenate((arr1,arr2),axis=1)
print(arr_new1)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [13]:
arr1=np.array([[1,2,3,4,5]])
print(arr1)
arr2=np.array([[6,7,8,9,10]])
print(arr2)
print()
arr_new=np.stack((arr1,arr2))
print(arr_new)
print()
arr_new_v=np.vstack((arr1,arr2))
print(arr_new_v)
print()
arr_new_h=np.hstack((arr1,arr2))
print(arr_new_h)
print()
arr_new_d=np.dstack((arr1,arr2))
print(arr_new_d)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2  3  4  5  6  7  8  9 10]]

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [14]:
arr=np.array([[10,20,30,40],[1,2,3,4]])
arr1=np.append(arr,[[10,20,30,40],[10,30,40,50]])
print(arr1)

[10 20 30 40  1  2  3  4 10 20 30 40 10 30 40 50]


In [3]:
arr1=np.array([10,20,30,40])
print(arr1)
arr2=np.array([100,200,300,400])
print(arr2)
arr_new=np.append(arr1,arr2)
print(arr_new)

[10 20 30 40]
[100 200 300 400]
[ 10  20  30  40 100 200 300 400]


In [4]:
arr1=np.array([[10,20,30,40],[50,60,70,80]])
print(arr1)
arr2=np.array([[100,200,300,400],[500,600,700,800]])
print(arr2)
arr_new=np.append(arr1,arr2)
print(arr_new)

[[10 20 30 40]
 [50 60 70 80]]
[[100 200 300 400]
 [500 600 700 800]]
[ 10  20  30  40  50  60  70  80 100 200 300 400 500 600 700 800]


In [5]:
arr1=np.array([[10,20,30],[40,50,60]])
print(arr1)
arr2=np.array([[100,200,300],[400,500,600]])
print(arr2)
arr_new=np.append(arr1,arr2,axis=0)
print(arr_new)

[[10 20 30]
 [40 50 60]]
[[100 200 300]
 [400 500 600]]
[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]
 [400 500 600]]


In [6]:
arr1=np.array([[10,20,30],[40,50,60]])
print(arr1)
arr2=np.array([[100,200,300],[400,500,600]])
print(arr2)
arr_new=np.append(arr1,arr2,axis=1)
print(arr_new)

[[10 20 30]
 [40 50 60]]
[[100 200 300]
 [400 500 600]]
[[ 10  20  30 100 200 300]
 [ 40  50  60 400 500 600]]


In [7]:
arr1=np.array([[10,20,30],[40,50,60]])
print(arr1)
arr2=np.array([[100,200],[400,500]])
print(arr2)
arr_new=np.append(arr1,arr2,axis=1)
print(arr_new)

[[10 20 30]
 [40 50 60]]
[[100 200]
 [400 500]]
[[ 10  20  30 100 200]
 [ 40  50  60 400 500]]


In [8]:
#split() - equal division
arr=np.array([10,20,30,40,50,60])
arr1=np.split(arr,3)
print(arr1)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [9]:
#array_split() - unequal division 
arr=np.array([10,20,30,40,50,60,70,80])
print(arr)
arr1=np.array_split(arr,3)
print(arr1)

[10 20 30 40 50 60 70 80]
[array([10, 20, 30]), array([40, 50, 60]), array([70, 80])]
